# Generated by Django 4.2.7 on 2024-01-06 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Split',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, max_length=2048)),
                ('category', models.CharField(choices=[('general', 'General'), ('bar', 'Bar'), ('breakfast', 'Breakfast'), ('dinner', 'Dinner'), ('launch', 'Launch'), ('coffee', 'Coffee'), ('electricity', 'Electricity'), ('water', 'Water'), ('gas', 'Gas'), ('cleaning', 'Cleaning'), ('internet', 'Internet'), ('mobile', 'Mobile'), ('rent', 'Rent'), ('gifts', 'Gifts'), ('games', 'Games')], max_length=64)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
            ],
        ),
        migrations.CreateModel(
            name='Spend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('split', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spends', to='split.split')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
